name: "local-dcs"
net: 0x02
genesis_param: 
  fee_per_tx_kb: 0
  consensus_algorithm: "bls"
  block_timestamp: "2019-11-29T00:00:00.000Z"
  tx_stake: "d0e731f55fa6c49f602807a6686a7ac769de4e04882bb5eaf8f4fe209f46535d"
committee_size:
  max_shard_committee_size: 12
  min_shard_committee_size: 4
  min_beacon_committee_size: 4
  max_beacon_committee_size: 7
  init_shard_committee_size: 4
  init_beacon_committee_size: 4
  shard_committee_size_key_list_v2: 4
  beacon_committee_size_key_list_v2: 4
  number_of_fixed_shard_block_validators: 4
block_time:
  min_beacon_block_interval: 10s 
  max_beacon_block_creation: 8s
  min_shard_block_interval: 10s
  max_shard_block_creation: 6s
staking_amount_shard: 1750000000000
active_shards: 1
basic_reward: 400000000
epoch_param:
  number_of_block_in_epoch: 10
  number_of_block_in_epoch_v2: 1000000000000
  epoch_v2_break_point: 1000000000000
  random_time: 5
  random_time_v2: 1000000000000
eth_contract_address: "0xE0D5e7217c6C4bc475404b26d763fAD3F14D2b86"
dao_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci" # community fund
centralized_website_payment_address: "12S5Lrs1XeQLbqN4ySyKtjAjd2d7sBP2tjFijzmp6avrrkQCNFMpkXm3FPzj2Wcu2ZNqJEmh9JriVuRErVwhuQnLmWSaggobEWsBEci"
swap_committee_param:
  offset: 1
  swap_offset: 1
  assign_offset: 2
consensus_param: 
  consensus_v2_epoch: 1
  staking_flow_v2_height: 1
  enable_slashing_height: 1
  enable_slashing_height_v2: 1
  assign_rule_v3_height: 1
  staking_flow_v3_height: 1
  block_producing_v3_height: 1000000000000
  timeslot: 10
  epoch_break_point_swap_new_key: 
    - 1000000000
beacon_height_break_point_burn_addr: 1
eth_remove_bridge_sig_epoch: 21920
replace_staking_tx_height: 1
bc_height_break_point_new_zkp: 1148608
enable_feature_flags:
  - 0: 1
  - 1: 0
portal_v3_height: 1000000000000
tx_pool_version: 0
geth_param: 
  host: "kovan.infura.io/v3/1138a1e99b154b10bae5c382ad894361"
  protocol: "https"
  port: ""
bsc_param:
  host: "https://data-seed-prebsc-1-s1.binance.org:8545"
is_enable_bpv3_stats: true