hosts:
    - http://127.0.0.1:20000/
    - http://127.0.0.1:20001/
    - http://127.0.0.1:20002/
    - http://127.0.0.1:20003/
    - http://127.0.0.1:20004/
    - http://127.0.0.1:20005/
    - http://127.0.0.1:20006/
    - http://127.0.0.1:20007/
    - http://127.0.0.1:20008/
    - http://127.0.0.1:20009/
    - http://127.0.0.1:20010/
    - http://127.0.0.1:20011/
miningkeys:
    - 12NjwfVK7YoBENaZwmHHPUaspK3uUtv3M22761TFk3H3FEuT83U
    - 12pLJqKTpcyQxdkUBthhydx2PKSt7G5YhBDRGjVWquGZLB8Mrvk
    - 1mGVTi2HmraVLx5vpLgpYGT9ZT76pNbb5Hh222hurZJf1257uE
    - 1vd6YYHi4MdPib8YymiFkdEHpZ3qNUKmqQVDGpwYYGgtDN3dhy
    - 16rj6Tbqt3cHjrGvkVaN4VGR87aQ3NM8kuHKQ5V6ciTna3N6CT
    - 1q8aqZVPCywGKDi5un6NuwDMEKk59GFTd89pkTSj3cpXFmFwDc
    - 1Vgz5qoz2Qkj462ApBhY3Q7NNQK6V8Q3oSTizaD52tSwTzDqwM
    - 1vGPif7nGLCdkS5Mvz3WF5LrhfAg7DQEiPDejUbPDjp1PN1iqG
    - 14VKR9zXbdNgEyjCeQC6QhK1MDFqvUxNHmh7HVh5P4RRiDts7m
    - 1hjGVkVm7k1YebYTChgt6GdawNtDBh6QHPCcrUzbVFnqr5WG8g
    - 12MqgWkPbbGg4LXmfPyEVqZcYzBuS1aouAnqdriJ1RxkW1sokmR
    - 1ZwJxDGzVF4kqYu9JkuvBSebn51KAZ875tbVNnfT9xtmKB6vD3
